// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_details.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HelpInfo_Hyperlink;
@class LocalizedMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum FieldViolation_ViolationType

typedef GPB_ENUM(FieldViolation_ViolationType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  FieldViolation_ViolationType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** A required field was not provided. */
  FieldViolation_ViolationType_MandatoryFieldMissing = 0,

  /** A field is invalid due to the value of another field. */
  FieldViolation_ViolationType_FieldConflict = 1,

  /** A field value is outside the specified range. */
  FieldViolation_ViolationType_OutOfRange = 2,

  /** A field value is not in the correct format. */
  FieldViolation_ViolationType_InvalidFormat = 3,

  /** A text field value is too short. */
  FieldViolation_ViolationType_TooShort = 4,

  /** A text field value is too long. */
  FieldViolation_ViolationType_TooLong = 5,

  /** Violation type is not otherwise listed. */
  FieldViolation_ViolationType_Other = 64,

  /** Violation type was not set. */
  FieldViolation_ViolationType_Unspecified = 99,
};

GPBEnumDescriptor *FieldViolation_ViolationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL FieldViolation_ViolationType_IsValidValue(int32_t value);

#pragma mark - ErrorDetailsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ErrorDetailsRoot : GPBRootObject
@end

#pragma mark - RetryInfo

typedef GPB_ENUM(RetryInfo_FieldNumber) {
  RetryInfo_FieldNumber_RetryDelayMs = 1,
};

/**
 * How quickly clients may retry the request for requests that allow retries.
 * Failure to respect this delay may indicate a misbehaving client.
 **/
GPB_FINAL @interface RetryInfo : GPBMessage

/** Mandatory. Clients should wait at least this long between retrying the same request. */
@property(nonatomic, readwrite) int32_t retryDelayMs;

@end

#pragma mark - RequestInfo

typedef GPB_ENUM(RequestInfo_FieldNumber) {
  RequestInfo_FieldNumber_RequestId = 1,
  RequestInfo_FieldNumber_RequestData = 2,
  RequestInfo_FieldNumber_AdditionalRequestData = 3,
};

/**
 * Information about the request that resulted in an error. This information is
 * particularly useful in streaming scenarios, in which the connection between
 * the request and response may not be obvious.
 **/
GPB_FINAL @interface RequestInfo : GPBMessage

/** Mandatory. Identifier of the original request, for example its OpenTracing ID. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

/** Optional. Relevant free format data from the original request, for troubleshooting. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestData;

/** Optional. Map of key,value pairs of free format data from the request. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *additionalRequestData;
/** The number of items in @c additionalRequestData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger additionalRequestData_Count;

@end

#pragma mark - HelpInfo

typedef GPB_ENUM(HelpInfo_FieldNumber) {
  HelpInfo_FieldNumber_LinksArray = 1,
};

/**
 * A reference to a help document that may be shown to end users to allow them
 * to take action based on the error or status response. For example, if the
 * request contained a numerical value that is out of range, this message may
 * point to the documentation that states the valid range.
 **/
GPB_FINAL @interface HelpInfo : GPBMessage

/** Optional. Set of links related to the enclosing message. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HelpInfo_Hyperlink*> *linksArray;
/** The number of items in @c linksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger linksArray_Count;

@end

#pragma mark - HelpInfo_Hyperlink

typedef GPB_ENUM(HelpInfo_Hyperlink_FieldNumber) {
  HelpInfo_Hyperlink_FieldNumber_Description_p = 1,
  HelpInfo_Hyperlink_FieldNumber_URL = 2,
};

/**
 * A link to a help message, including a localized description of the link.
 **/
GPB_FINAL @interface HelpInfo_Hyperlink : GPBMessage

/**
 * Optional. A description of the link in a specific language (locale). By default,
 * the server handling the URL manages language selection and detection.
 **/
@property(nonatomic, readwrite, strong, null_resettable) LocalizedMessage *description_p;
/** Test to see if @c description_p has been set. */
@property(nonatomic, readwrite) BOOL hasDescription_p;

/**
 * Mandatory. The URL to offer to the client, containing help information. If a
 * description is present, this URL should use (or offer) the same locale.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - LocalizedMessage

typedef GPB_ENUM(LocalizedMessage_FieldNumber) {
  LocalizedMessage_FieldNumber_Locale = 1,
  LocalizedMessage_FieldNumber_Message = 2,
  LocalizedMessage_FieldNumber_MessageResourceId = 3,
};

/**
 * A help message in a language other than American English. The default
 * locale is provided by the server, for example the browser's preferred
 * language or a user-specific locale. All Nuance gRPC APIs that want the
 * server to provide localized errors must accept the HTTP "Accept-Language"
 * header or application-specific language settings, if supported.
 **/
GPB_FINAL @interface LocalizedMessage : GPBMessage

/**
 * Required. The locale used following the specification defined at
 * https://www.rfc-editor.org/info/rfc5646.
 * Examples are: "en-US", "fr-CH", "es-MX"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

/** Required. The message text in the locale specified. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** Optional. A message identifier, allowing related messages to be provided if needed. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageResourceId;

@end

#pragma mark - FieldViolation

typedef GPB_ENUM(FieldViolation_FieldNumber) {
  FieldViolation_FieldNumber_Field = 1,
  FieldViolation_FieldNumber_RelFieldArray = 2,
  FieldViolation_FieldNumber_UserMessage = 3,
  FieldViolation_FieldNumber_Message = 4,
  FieldViolation_FieldNumber_InvalidValue = 5,
  FieldViolation_FieldNumber_Violation = 6,
};

/**
 * Information about a field or fields containing errors.
 **/
GPB_FINAL @interface FieldViolation : GPBMessage

/** Required. The name of the field in violation as package.type[.type].field. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *field;

/**
 * Optional. The names of related fields in violation as:
 * package.type[.type].field.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *relFieldArray;
/** The number of items in @c relFieldArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger relFieldArray_Count;

/** Optional. An error message in a language other than English. */
@property(nonatomic, readwrite, strong, null_resettable) LocalizedMessage *userMessage;
/** Test to see if @c userMessage has been set. */
@property(nonatomic, readwrite) BOOL hasUserMessage;

/** Required. An error message in American English. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/**
 * Optional. The invalid value of the field in violation. (Convert non-string data
 * types to string.)
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *invalidValue;

/**
 * Required. The reason (enum) a field is invalid. Can be used for automated error
 * handling by the client.
 **/
@property(nonatomic, readwrite) FieldViolation_ViolationType violation;

@end

/**
 * Fetches the raw value of a @c FieldViolation's @c violation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FieldViolation_Violation_RawValue(FieldViolation *message);
/**
 * Sets the raw value of an @c FieldViolation's @c violation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFieldViolation_Violation_RawValue(FieldViolation *message, int32_t value);

#pragma mark - StatusDetail

typedef GPB_ENUM(StatusDetail_FieldNumber) {
  StatusDetail_FieldNumber_Message = 1,
  StatusDetail_FieldNumber_UserMessage = 2,
  StatusDetail_FieldNumber_Extras = 3,
};

/**
 * A status message may have additional details. Usually those details would
 * represent a list of underlying causes for the status (typically an error). These
 * details are different from the field violations. The field violations point to
 * the fields in the original request while these details are usually expected
 * not to be directly connected with the request parameters.
 **/
GPB_FINAL @interface StatusDetail : GPBMessage

/** Optional. US English message. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** Optional. Localized status detail message. */
@property(nonatomic, readwrite, strong, null_resettable) LocalizedMessage *userMessage;
/** Test to see if @c userMessage has been set. */
@property(nonatomic, readwrite) BOOL hasUserMessage;

/** Optional. Extra application-specific information provided as map. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extras;
/** The number of items in @c extras without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extras_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
