// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: nuance_tts.proto

#import <Foundation/Foundation.h>

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "NuanceTts.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import <ProtoRPC/ProtoService.h>
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriteable.h>
#import <RxLibrary/GRXWriter.h>
#endif

@class TTSGetVoicesRequest;
@class TTSGetVoicesResponse;
@class TTSSynthesisRequest;
@class TTSSynthesisResponse;
@class TTSUnarySynthesisResponse;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol TTSSynthesizer2 <NSObject>

#pragma mark GetVoices(GetVoicesRequest) returns (GetVoicesResponse)

- (GRPCUnaryProtoCall *)getVoicesWithMessage:(TTSGetVoicesRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark Synthesize(SynthesisRequest) returns (stream SynthesisResponse)

- (GRPCUnaryProtoCall *)synthesizeWithMessage:(TTSSynthesisRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark UnarySynthesize(SynthesisRequest) returns (UnarySynthesisResponse)

- (GRPCUnaryProtoCall *)unarySynthesizeWithMessage:(TTSSynthesisRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol TTSSynthesizer <NSObject>

#pragma mark GetVoices(GetVoicesRequest) returns (GetVoicesResponse)

- (void)getVoicesWithRequest:(TTSGetVoicesRequest *)request handler:(void(^)(TTSGetVoicesResponse *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToGetVoicesWithRequest:(TTSGetVoicesRequest *)request handler:(void(^)(TTSGetVoicesResponse *_Nullable response, NSError *_Nullable error))handler;


#pragma mark Synthesize(SynthesisRequest) returns (stream SynthesisResponse)

- (void)synthesizeWithRequest:(TTSSynthesisRequest *)request eventHandler:(void(^)(BOOL done, TTSSynthesisResponse *_Nullable response, NSError *_Nullable error))eventHandler;

- (GRPCProtoCall *)RPCToSynthesizeWithRequest:(TTSSynthesisRequest *)request eventHandler:(void(^)(BOOL done, TTSSynthesisResponse *_Nullable response, NSError *_Nullable error))eventHandler;


#pragma mark UnarySynthesize(SynthesisRequest) returns (UnarySynthesisResponse)

- (void)unarySynthesizeWithRequest:(TTSSynthesisRequest *)request handler:(void(^)(TTSUnarySynthesisResponse *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToUnarySynthesizeWithRequest:(TTSSynthesisRequest *)request handler:(void(^)(TTSUnarySynthesisResponse *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface TTSSynthesizer : GRPCProtoService<TTSSynthesizer2, TTSSynthesizer>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END

