// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: nuance_tts.proto

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import "NuanceTts.pbrpc.h"
#import "NuanceTts.pbobjc.h"
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriter+Immediate.h>


@implementation TTSSynthesizer

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"

// Designated initializer
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [super initWithHost:host
                 packageName:@"nuance.tts.v1"
                 serviceName:@"Synthesizer"
                 callOptions:callOptions];
}

- (instancetype)initWithHost:(NSString *)host {
  return [super initWithHost:host
                 packageName:@"nuance.tts.v1"
                 serviceName:@"Synthesizer"];
}

#pragma clang diagnostic pop

// Override superclass initializer to disallow different package and service names.
- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName {
  return [self initWithHost:host];
}

- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName
                 callOptions:(GRPCCallOptions *)callOptions {
  return [self initWithHost:host callOptions:callOptions];
}

#pragma mark - Class Methods

+ (instancetype)serviceWithHost:(NSString *)host {
  return [[self alloc] initWithHost:host];
}

+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [[self alloc] initWithHost:host callOptions:callOptions];
}

#pragma mark - Method Implementations

#pragma mark GetVoices(GetVoicesRequest) returns (GetVoicesResponse)

- (void)getVoicesWithRequest:(TTSGetVoicesRequest *)request handler:(void(^)(TTSGetVoicesResponse *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToGetVoicesWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToGetVoicesWithRequest:(TTSGetVoicesRequest *)request handler:(void(^)(TTSGetVoicesResponse *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"GetVoices"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[TTSGetVoicesResponse class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)getVoicesWithMessage:(TTSGetVoicesRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"GetVoices"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[TTSGetVoicesResponse class]];
}

#pragma mark Synthesize(SynthesisRequest) returns (stream SynthesisResponse)

- (void)synthesizeWithRequest:(TTSSynthesisRequest *)request eventHandler:(void(^)(BOOL done, TTSSynthesisResponse *_Nullable response, NSError *_Nullable error))eventHandler{
  [[self RPCToSynthesizeWithRequest:request eventHandler:eventHandler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToSynthesizeWithRequest:(TTSSynthesisRequest *)request eventHandler:(void(^)(BOOL done, TTSSynthesisResponse *_Nullable response, NSError *_Nullable error))eventHandler{
  return [self RPCToMethod:@"Synthesize"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[TTSSynthesisResponse class]
        responsesWriteable:[GRXWriteable writeableWithEventHandler:eventHandler]];
}
- (GRPCUnaryProtoCall *)synthesizeWithMessage:(TTSSynthesisRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"Synthesize"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[TTSSynthesisResponse class]];
}

#pragma mark UnarySynthesize(SynthesisRequest) returns (UnarySynthesisResponse)

- (void)unarySynthesizeWithRequest:(TTSSynthesisRequest *)request handler:(void(^)(TTSUnarySynthesisResponse *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToUnarySynthesizeWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToUnarySynthesizeWithRequest:(TTSSynthesisRequest *)request handler:(void(^)(TTSUnarySynthesisResponse *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"UnarySynthesize"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[TTSUnarySynthesisResponse class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)unarySynthesizeWithMessage:(TTSSynthesisRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"UnarySynthesize"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[TTSUnarySynthesisResponse class]];
}

@end
#endif
