// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;
@class InterpretResult;
@class NLUInterpretationInput;
@class NLUInterpretationParameters;
@class NLUInterpretationResource;
@class NLUResourceReference;
@class NLUStatus;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NLUEnumInterpretationResultType

/**
 * *
 * Format of interpretations result.  Included in
 * [InterpretationParameters](#interpretationparameters).
 **/
typedef GPB_ENUM(NLUEnumInterpretationResultType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NLUEnumInterpretationResultType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Default. Same as SINGLE_INTENT. */
  NLUEnumInterpretationResultType_Undefined = 0,

  /** Always return a single-intent interpretation. */
  NLUEnumInterpretationResultType_SingleIntent = 1,

  /** Always return multi-intent interpretation. */
  NLUEnumInterpretationResultType_MultiIntent = 2,
};

GPBEnumDescriptor *NLUEnumInterpretationResultType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NLUEnumInterpretationResultType_IsValidValue(int32_t value);

#pragma mark - Enum NLUEnumInterpretationInputLoggingMode

/**
 * *
 * Format for input in the diagnostic logs.  Included in
 * [InterpretationParameters](#interpretationparameters).
 **/
typedef GPB_ENUM(NLUEnumInterpretationInputLoggingMode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NLUEnumInterpretationInputLoggingMode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Default. Log the literal text of the input. */
  NLUEnumInterpretationInputLoggingMode_Plaintext = 0,

  /** Input is replaced with "value suppressed." */
  NLUEnumInterpretationInputLoggingMode_Suppressed = 9,
};

GPBEnumDescriptor *NLUEnumInterpretationInputLoggingMode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NLUEnumInterpretationInputLoggingMode_IsValidValue(int32_t value);

#pragma mark - Enum NLUEnumResourceType

/**
 * *
 * Specifies a model, wordset, or a compiled wordset. Included in
 * [ResourceReference](#resourcereference).  Use the default,
 * UNDEFINED_RESOURCE_TYPE, to determine the type from the
 * content-type header returned by the resource's server.
 **/
typedef GPB_ENUM(NLUEnumResourceType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NLUEnumResourceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Default. Use the content-type header from the resource's server to determine the type. */
  NLUEnumResourceType_UndefinedResourceType = 0,

  /** A semantic model from Mix.nlu. */
  NLUEnumResourceType_SemanticModel = 1,

  /** Currently unsupported. Use InterpretationResource - inline_wordset. */
  NLUEnumResourceType_Wordset = 2,

  /** A compiled wordset associated to a specific semantic model. */
  NLUEnumResourceType_CompiledWordset = 3,
};

GPBEnumDescriptor *NLUEnumResourceType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NLUEnumResourceType_IsValidValue(int32_t value);

#pragma mark - NLURuntimeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NLURuntimeRoot : GPBRootObject
@end

#pragma mark - NLUInterpretRequest

typedef GPB_ENUM(NLUInterpretRequest_FieldNumber) {
  NLUInterpretRequest_FieldNumber_Parameters = 1,
  NLUInterpretRequest_FieldNumber_Model = 2,
  NLUInterpretRequest_FieldNumber_ResourcesArray = 3,
  NLUInterpretRequest_FieldNumber_ClientData = 4,
  NLUInterpretRequest_FieldNumber_UserId = 5,
  NLUInterpretRequest_FieldNumber_Input = 10,
};

/**
 * *
 * The input to interpret, and parameters, model, extra resources, and
 * client tags. Included in the [Nlu](#nlu) service.
 **/
GPB_FINAL @interface NLUInterpretRequest : GPBMessage

/** Optional parameters for the interpretation. */
@property(nonatomic, readwrite, strong, null_resettable) NLUInterpretationParameters *parameters;
/** Test to see if @c parameters has been set. */
@property(nonatomic, readwrite) BOOL hasParameters;

/** Required semantic model to perform the interpretation. */
@property(nonatomic, readwrite, strong, null_resettable) NLUResourceReference *model;
/** Test to see if @c model has been set. */
@property(nonatomic, readwrite) BOOL hasModel;

/** Repeated. Optional resources to customize the interpretation. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NLUInterpretationResource*> *resourcesArray;
/** The number of items in @c resourcesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resourcesArray_Count;

/** Optional key-value pairs to log. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *clientData;
/** The number of items in @c clientData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger clientData_Count;

/** Optional. Identifies a particular user within an application. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** Required input to interpret. */
@property(nonatomic, readwrite, strong, null_resettable) NLUInterpretationInput *input;
/** Test to see if @c input has been set. */
@property(nonatomic, readwrite) BOOL hasInput;

@end

#pragma mark - NLUInterpretationParameters

typedef GPB_ENUM(NLUInterpretationParameters_FieldNumber) {
  NLUInterpretationParameters_FieldNumber_InterpretationResultType = 1,
  NLUInterpretationParameters_FieldNumber_InterpretationInputLoggingMode = 2,
  NLUInterpretationParameters_FieldNumber_PostProcessingScriptParameters = 3,
  NLUInterpretationParameters_FieldNumber_MaxInterpretations = 12,
};

/**
 * *
 * Optional parameters controlling the interpretation. Included in
 * [InterpretRequest](#interpretrequest).
 **/
GPB_FINAL @interface NLUInterpretationParameters : GPBMessage

/** Format of interpretation result. Default is SINGLE_INTENT. */
@property(nonatomic, readwrite) NLUEnumInterpretationResultType interpretationResultType;

/** Format for input in the log. Default is PLAINTEXT. */
@property(nonatomic, readwrite) NLUEnumInterpretationInputLoggingMode interpretationInputLoggingMode;

/** Parameters to pass to custom post-processing ECMA scripts in the model. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *postProcessingScriptParameters;
/** The number of items in @c postProcessingScriptParameters without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postProcessingScriptParameters_Count;

/** Maximum interpretations for the result. Default is 0 for the NLU server's configured setting. */
@property(nonatomic, readwrite) uint32_t maxInterpretations;

@end

/**
 * Fetches the raw value of a @c NLUInterpretationParameters's @c interpretationResultType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NLUInterpretationParameters_InterpretationResultType_RawValue(NLUInterpretationParameters *message);
/**
 * Sets the raw value of an @c NLUInterpretationParameters's @c interpretationResultType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNLUInterpretationParameters_InterpretationResultType_RawValue(NLUInterpretationParameters *message, int32_t value);

/**
 * Fetches the raw value of a @c NLUInterpretationParameters's @c interpretationInputLoggingMode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NLUInterpretationParameters_InterpretationInputLoggingMode_RawValue(NLUInterpretationParameters *message);
/**
 * Sets the raw value of an @c NLUInterpretationParameters's @c interpretationInputLoggingMode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNLUInterpretationParameters_InterpretationInputLoggingMode_RawValue(NLUInterpretationParameters *message, int32_t value);

#pragma mark - NLUInterpretationResource

typedef GPB_ENUM(NLUInterpretationResource_FieldNumber) {
  NLUInterpretationResource_FieldNumber_ExternalReference = 1,
  NLUInterpretationResource_FieldNumber_InlineWordset = 2,
};

typedef GPB_ENUM(NLUInterpretationResource_ResourceUnion_OneOfCase) {
  NLUInterpretationResource_ResourceUnion_OneOfCase_GPBUnsetOneOfCase = 0,
  NLUInterpretationResource_ResourceUnion_OneOfCase_ExternalReference = 1,
  NLUInterpretationResource_ResourceUnion_OneOfCase_InlineWordset = 2,
};

/**
 * *
 * A resource to customize the interpretation. Included in
 * [InterpretRequest](#interpretrequest).
 **/
GPB_FINAL @interface NLUInterpretationResource : GPBMessage

@property(nonatomic, readonly) NLUInterpretationResource_ResourceUnion_OneOfCase resourceUnionOneOfCase;

/** External resource. */
@property(nonatomic, readwrite, strong, null_resettable) NLUResourceReference *externalReference;

/** Inline wordset, in JSON. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *inlineWordset;

@end

/**
 * Clears whatever value was set for the oneof 'resourceUnion'.
 **/
void NLUInterpretationResource_ClearResourceUnionOneOfCase(NLUInterpretationResource *message);

#pragma mark - NLUResourceReference

typedef GPB_ENUM(NLUResourceReference_FieldNumber) {
  NLUResourceReference_FieldNumber_Type = 1,
  NLUResourceReference_FieldNumber_Uri = 2,
  NLUResourceReference_FieldNumber_RequestTimeoutMs = 7,
  NLUResourceReference_FieldNumber_Headers = 8,
};

/**
 * *
 * Parameters to fetch an external resource. Included in
 * [InterpretRequest](#interpretrequest) and
 * [InterpretationResource](#interpretationresource).
 **/
GPB_FINAL @interface NLUResourceReference : GPBMessage

/** Resource type. */
@property(nonatomic, readwrite) NLUEnumResourceType type;

/** Location or name of the resource. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

/** Time, in ms, to wait for a response from the hosting server. Default is 0 for the NLU server's configured setting. */
@property(nonatomic, readwrite) uint32_t requestTimeoutMs;

/** Optional map of headers to transmit to the server hosting the resource. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *headers;
/** The number of items in @c headers without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger headers_Count;

@end

/**
 * Fetches the raw value of a @c NLUResourceReference's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NLUResourceReference_Type_RawValue(NLUResourceReference *message);
/**
 * Sets the raw value of an @c NLUResourceReference's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNLUResourceReference_Type_RawValue(NLUResourceReference *message, int32_t value);

#pragma mark - NLUInterpretationInput

typedef GPB_ENUM(NLUInterpretationInput_FieldNumber) {
  NLUInterpretationInput_FieldNumber_Text = 1,
  NLUInterpretationInput_FieldNumber_AsrResult = 2,
};

typedef GPB_ENUM(NLUInterpretationInput_InputUnion_OneOfCase) {
  NLUInterpretationInput_InputUnion_OneOfCase_GPBUnsetOneOfCase = 0,
  NLUInterpretationInput_InputUnion_OneOfCase_Text = 1,
  NLUInterpretationInput_InputUnion_OneOfCase_AsrResult = 2,
};

/**
 * *
 * Input to interpret. Included in
 * [InterpretRequest](#interpretrequest). Use either text or the
 * [result](../../asr-grpc/v1/index.html#result) from ASR as a
 * Service.
 **/
GPB_FINAL @interface NLUInterpretationInput : GPBMessage

@property(nonatomic, readonly) NLUInterpretationInput_InputUnion_OneOfCase inputUnionOneOfCase;

/** Text input. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

/** Result from ASR as a Service. */
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *asrResult;

@end

/**
 * Clears whatever value was set for the oneof 'inputUnion'.
 **/
void NLUInterpretationInput_ClearInputUnionOneOfCase(NLUInterpretationInput *message);

#pragma mark - NLUInterpretResponse

typedef GPB_ENUM(NLUInterpretResponse_FieldNumber) {
  NLUInterpretResponse_FieldNumber_Status = 1,
  NLUInterpretResponse_FieldNumber_Result = 3,
  NLUInterpretResponse_FieldNumber_Metadata = 13,
};

/**
 * *
 * The interpretation result. Included in the [Nlu](#nlu) service.
 **/
GPB_FINAL @interface NLUInterpretResponse : GPBMessage

/** Whether the request was successful. The 200 code means success, other values indicate an error. */
@property(nonatomic, readwrite, strong, null_resettable) NLUStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

/** The result of the interpretation. */
@property(nonatomic, readwrite, strong, null_resettable) InterpretResult *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

/** Optional metadata attached to the response. For internal use only. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, GPBAny*> *metadata;
/** The number of items in @c metadata without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger metadata_Count;

@end

#pragma mark - NLUStatus

typedef GPB_ENUM(NLUStatus_FieldNumber) {
  NLUStatus_FieldNumber_Code = 1,
  NLUStatus_FieldNumber_Message = 2,
  NLUStatus_FieldNumber_Details = 3,
};

/**
 * *
 * A Status message indicates whether the request was successful or
 * reports errors that occurred during the request.  Included in
 * [InterpretResponse](#interpretresponse).
 **/
GPB_FINAL @interface NLUStatus : GPBMessage

/** HTTP status code. The 200 code means success, other values indicate an error. */
@property(nonatomic, readwrite) uint32_t code;

/** Brief description of the status. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** Longer description if available. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *details;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
