// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: runtime.proto

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import "Runtime.pbrpc.h"
#import "Runtime.pbobjc.h"
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriter+Immediate.h>

#import "Result.pbobjc.h"
#import "google/api/Annotations.pbobjc.h"
#if defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS) && GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBAny.pbobjc.h>
#else
#import "GPBAny.pbobjc.h"
#endif

@implementation NLURuntime

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"

// Designated initializer
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [super initWithHost:host
                 packageName:@"nuance.nlu.v1"
                 serviceName:@"Runtime"
                 callOptions:callOptions];
}

- (instancetype)initWithHost:(NSString *)host {
  return [super initWithHost:host
                 packageName:@"nuance.nlu.v1"
                 serviceName:@"Runtime"];
}

#pragma clang diagnostic pop

// Override superclass initializer to disallow different package and service names.
- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName {
  return [self initWithHost:host];
}

- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName
                 callOptions:(GRPCCallOptions *)callOptions {
  return [self initWithHost:host callOptions:callOptions];
}

#pragma mark - Class Methods

+ (instancetype)serviceWithHost:(NSString *)host {
  return [[self alloc] initWithHost:host];
}

+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [[self alloc] initWithHost:host callOptions:callOptions];
}

#pragma mark - Method Implementations

#pragma mark Interpret(InterpretRequest) returns (InterpretResponse)

/**
 * Starts an interpretation request and returns a response.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)interpretWithRequest:(NLUInterpretRequest *)request handler:(void(^)(NLUInterpretResponse *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToInterpretWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
/**
 * Starts an interpretation request and returns a response.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToInterpretWithRequest:(NLUInterpretRequest *)request handler:(void(^)(NLUInterpretResponse *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"Interpret"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[NLUInterpretResponse class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
/**
 * Starts an interpretation request and returns a response.
 */
- (GRPCUnaryProtoCall *)interpretWithMessage:(NLUInterpretRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"Interpret"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[NLUInterpretResponse class]];
}

@end
#endif
