source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'NuanceMix' do
  # Depend on the generated HelloWorld library.
  pod 'NuanceMix', :path => '.'
end
